:down:
  :max_redirects: 2
  :open_timeout: 30
  :read_timeout: 30
  :max_size: 5242880 # 5 * 1024 * 1024 (5MB)
  :content_type:
    - image/jpeg
    - image/jpg
    - image/png
    - image/bmp
    - image/gif
    - image/tiff

:thread_pool:
  :min_threads: 2